a=int(input('introduceti nr. de oua pe care le face 1 gaina intr-o zi='))
b=int(input('introduceti nr. de oua pe care le face a 2 gaina intr-o zi='))
c=int(input('introduceti nr. de oua pe care le face a 3 gaina intr-o zi='))
d=int(input('introduceti nr. de oua pe care le face a 4 gaina intr-o zi='))
print('intr-o saptamana se obtin' , 7*(a+b+c+d) )